### ISSUE TITLE
Downloads the same song

### ISSUE THREAD

**Issue by kleagon** [J05HI/DeezLoadr#19]
I have tested it on Windows and Mac, and it is only happening on Mac.
No matter what album or song URL you use, it will download the same random song. Yesterday it was a different song, today it seems to be another one, but it is the same song.
Also, it would be better to have files organized based on the album artist, not the track artists: /Album Artist/Album Name/Song Title
Thank you for the great work on this.

<img width="408" alt="screenshot" src="https://user-images.githubusercontent.com/33985293/33232377-604de998-d1d3-11e7-8ff1-9242554d85f4.png">

**Comment by azgul** [comment]
> Also, it would be better to have files organized based on the album artist, not the track artists: /Album Artist/Album Name/Song Title

https://github.com/J05HI/DeezLoadr/pull/16

**Comment by realdylancarr** [comment]
Having the same issue. But unlike OP I am having it on Windows.

Same song too.

**Comment by kingofwap** [comment]
Album artist should be fine

**Comment by BlueCrystal** [comment]
Same thing happens with me on Linux and Windows. However, the song listed in the original post (Cole Swindell - Get Me Some Of That" is now ""Luis Miguel - ¿Por Qué Te Conocí?".

Doesn't make a difference if its an album link or a track link.

**Comment by realdylancarr** [comment]
Ahhh I see a rep pattern now. 

Deezer features various songs on a daily basis. The program is picking up on the featured song instead of the one linked - perhaps Deezer changed something with their API recently? 

If you go on Deezer.com whilst logged in the featured song is already selected in the bottom left corner. It may be region-based, not sure.


Doesn't happen on mobile.

**Comment by omniusaspirer** [comment]
It's happening because many of us (not sure why not all of us) are hitting a mandatory log in page and not actually going to the track page when you hit this bit of code:

`return request(format('http://www.deezer.com/track/%d', id)).then((htmlString) => {
        const PLAYER_INIT = htmlString.match(/track: ({.+}),/);
        const trackInfos = JSON.parse(PLAYER_INIT[1]).data[0];
        const trackQuality = getValidTrackQuality(trackInfos);`

I've been dicking around for the last hour trying to pass all the cookies from a logged in browser session through this request but I seem to be missing something because I'm still slamming into this redirect. In an actual browser, after logging in the links to each track work correctly.

**Comment by kleagon** [comment]
The Windows version that is currently working, it is on a server in Canada. I believe Deezer is forcing US users to create an account in order to access the service, and maybe that is why this is not affecting all users?

**Comment by realdylancarr** [comment]
Yep, looks like that is it! I was using a Chicago-based VPN originally but switched to Toronto and it's workign now.

**Comment by BlueCrystal** [comment]
Looks like it's the same thing for me. I switched from a US location to a Luxembourg server and it downloaded 2 files I threw at it. However, now there appears to be a separate issue (maybe?), where anything downloaded using the FLAC option gives you a FLAC__STREAM_DECODER_SEARCH_FOR_METADATA decoding issue. I guess I'll make a new issue for this.

**Comment by J05HI** [comment]
This problem is really strange :(

**Comment by tazitus** [comment]
Maybe getting the track info from api.deezer.com/track/[id] instead of parsing an html page would help.

**Comment by omniusaspirer** [comment]
If you pull down a copy of Deezloader from one of the many github repos and edit a few key points you can get the normal Deezloader downloading FLAC, which is what I've done for now while some of the kinks get worked out of this version. 

`        var id = json["SNG_ID"];
        var md5Origin = json["MD5_ORIGIN"];
        var format = 9;
        if(json["FILESIZE_FLAC"] <= 0) {
          if(json["FILESIZE_MP3_320"] > 0) {
            format = 5;
          } else {
            format = 1;
          }`

That's the big one. You'll need to tweak some stuff in server.js as well to give it sensible download locations and get the filetype set as FLAC instead of mp3. I'm sure it's messing up the tagging, but I tag everything with Picard anyways so that hasn't impacted me.

**Comment by tazitus** [comment]
I also did that a few days ago. While the files played just fine, when testing with `flac -wt` they showed various errors.

**Comment by omniusaspirer** [comment]
Could you post the output here? Not familiar with the tool you're using, I just threw them in a spectrograph and they seemed to check out as genuine, but I did notice the actual file sizes don't align with those seen in allegedly identical FLACs on Soulseek.

**Comment by omniusaspirer** [comment]
Can someone in this thread please upload a copy of Kendrick Lamar's "Wesley's Theory" downloaded with this Deezloadr variant? Alternatively, call "flac -wt" on it yourself and let me know if it works or throws a LOST_SYNC error.

**Comment by J05HI** [comment]
@tazitus
Yeah that must be the solution.
Will try it in the evening :)

**Comment by J05HI** [comment]
Should be fixed now with [https://github.com/J05HI/DeezLoadr/commit/d1eb9205a3e4c12d02e04b310a190ddcda486d16](https://github.com/J05HI/DeezLoadr/commit/d1eb9205a3e4c12d02e04b310a190ddcda486d16)
Please give feedback :)

**Comment by kleagon** [comment]
@J05HI All working now! 
But with this latest build I am getting the following error on certain tracks
`♫ Deezer URL: (node:85415) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added. Use emitter.setMaxListeners() to increase limit
`
It looks like the track finishes downloading but I have not checked if it is complete.

**Comment by J05HI** [comment]
@kleagon 
Fixed as [https://github.com/J05HI/DeezLoadr/issues/44](https://github.com/J05HI/DeezLoadr/issues/44) with commit [https://github.com/J05HI/DeezLoadr/commit/73a701ba06f619d53e0fd318c2c90aabe994ab86](https://github.com/J05HI/DeezLoadr/commit/73a701ba06f619d53e0fd318c2c90aabe994ab86) :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
