### ISSUE TITLE
Duplicate artists

### ISSUE THREAD

**Issue by ghost** [J05HI/DeezLoadr#56]
The artist name is duplicated, try it with this example.

**Comment by J05HI** [comment]
@oO-u-Oo 
You mean "Oscar Mulero, Oscar Mulero and Inigo Kennedy, Inigo Kennedy"?
Can't do anything about that. It's information from Deezer.

**Comment by oO-u-Oo** [comment]
TripleFrequency if you have managed to fix it.
https://github.com/TripleFrequency/AthamePlugin.Deezer/issues/7

**Comment by J05HI** [comment]
@oO-u-Oo
Great! I'll take a look at it :)

**Comment by TripleFrequency** [comment]
Yeah I wasn't entirely happy with the solution, I had to brute-force it in a way. When generating the Artist's name, I simply rejected names that contained " and " or " & ".

**Comment by J05HI** [comment]
@TripleFrequency
Yeah but I would split it at this character and search if one of the other artists contains one of the splitted ones.

**Comment by TripleFrequency** [comment]
Interesting idea. That would almost definitely remove the possibility of invalidating names that *contain* those sequences.

**Comment by TripleFrequency** [comment]
You can see my solution to the problem in [AthamePlugin.Deezer/`055c698`](https://github.com/TripleFrequency/AthamePlugin.Deezer/commit/20d02b9ea007a18d58da0dbe64b171fb6eff556a), @J05HI.

**Comment by J05HI** [comment]
@TripleFrequency
Yeah you could add that too :)

**Comment by TripleFrequency** [comment]
If you go that route, I would recommend you follow [my revision, as well](https://github.com/TripleFrequency/AthamePlugin.Deezer/commit/42d1ddb9f120cd9075d2c26d4f29d9331d811def). Basically, normalize the title by making it lowercase and removing special characters (I did this via regex). The changing to use a "change list" instead of my original implementation is a way to get around an issue with modifying the list used in a foreach loop, but you could probably get away with iterating backwards over the artist list.

**Comment by J05HI** [comment]
@TripleFrequency
Great!
Thanks!!!

**Comment by J05HI** [comment]
@ghost @TripleFrequency 
Implemented :)

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
